service: authentication-service-serverless

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  EnsureAuthenticated:
    handler: src/infra/serverless/functions/EnsureAuthenticated.handle
  EnsureAdmin:
    handler: src/infra/serverless/functions/EnsureAdmin.handle
  SignInUser:
    handler: src/infra/serverless/functions/SignInUser.handle
    events:
      - http:
          path: /sessions
          method: POST
  hello:
    handler: src/infra/serverless/functions/hello.handle
    events:
      - http:
          path: /
          method: GET

custom:
  dotenv:
    path: ".env.development"
    include:
      - TOKEN_SECRET_KEY