version: "3.7"

services:
  ecommerce_database:
    image: postgres
    container_name: ecommerce_database
    restart: always
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce_database
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: ecommerce-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - ecommerce_database
    depends_on:
      - ecommerce_database

volumes:
  pgdata:
    driver: local
