version: "3.7"

services:
  product_service_database:
    image: postgres
    container_name: product_service_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product_service_database
    volumes:
      - pgdata:/data/postgres
  product_service_test_database:
    image: postgres
    container_name: product_service_test_database
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=prisma_test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=product_service_test_database
    volumes:
      - pgdata:/data/postgres
  product_service_api:
    build: .
    container_name: product_service_api
    ports:
      - 3334:3334
    volumes:
      - .:/usr/app
    links:
      - product_service_database
    depends_on:
      - product_service_database

volumes:
  pgdata:
    driver: local
