service: product-service-serverless

frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  region: sa-east-1
  vpc:
    securityGroupIds:
      - ${file(./serverless-secrets.json):SECURITY_GROUP_ID}
    subnetIds:
      - ${file(./serverless-secrets.json):SUBNET_ID1}
      - ${file(./serverless-secrets.json):SUBNET_ID2}
      - ${file(./serverless-secrets.json):SUBNET_ID3}

functions:
  CreateCategory:
    handler: src/infra/serverless/functions/CreateCategory.handle
    events:
      - http:
          method: POST
          path: /categories
          cors: true
  DeleteCategory:
    handler: src/infra/serverless/functions/DeleteCategory.handle
    events:
      - http:
          method: DELETE
          path: /categories/delete/{id}
          cors: true
  UpdateCategory:
    handler: src/infra/serverless/functions/UpdateCategory.handle
    events:
      - http:
          method: PUT
          path: /categories/update/{id}
          cors: true
  CreateProduct:
    handler: src/infra/serverless/functions/CreateProduct.handle
    events:
      - http:
          method: POST
          path: /products
          cors: true
  
package:
  exclude:
    - ./node_modules/prisma/**

custom:
  dotenv:
    path: ".env.development"