name: CI

on:

  push:
    branches: [ main ]
    paths:
      - services/UserService/**
      - services/ProductService/**
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.0'
        
      - name: Install Dependencies
        run: |
          cd ./services/UserService
          yarn
          cd ../ProductService
          yarn
      
      - name: Build
        run: |
          cd ./services/UserService
          yarn build
          cd ../ProductService
          yarn build
          
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !services/UserService/node_modules, !services/ProductService/node_modules"
          target: "~/app/GoTech"
          
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH="$PATH:/home/***/.nvm/versions/node/v16.14.0/bin/pm2:/home/***/.nvm/versions/node/v16.14.0/bin/pm2"
            cd ~/app/GoTech/services/UserService
            yarn
            yarn prisma:migrate
            pm2 restart UserService
            cd ../ProductService
            yarn
            yarn prisma:migrate
            pm2 restart ProductService
